(async()=>{try{
const urls=['./app.bundle.part0.b64','./app.bundle.part1.b64','./app.bundle.part2.b64'];
const parts=await Promise.all(urls.map(async u=>{const r=await fetch(u,{cache:'no-cache'});if(!r.ok)throw new Error(`App bundle load failed: ${r.status}`);return r.text()}));
const bin=atob(parts.join(''));const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);
if(typeof DecompressionStream==='undefined')throw new Error('This browser does not support gzip decompression');
const code=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();(0,eval)(code);
const css=href=>{const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)};
const load=src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.body.appendChild(s)});
css('./v10.css');
await load('./data/reference-renders-v10.js');
await load('./data/reference-renders-tx-v10.1.js');
await load('./v10-patch.js');
css('./v11.css');
await load('./v11-patch.js');
css('./cloud-sync.css');
await load('./cloud-sync.js');
css('./v12.css');
await load('./v12-patch.js');
css('./v12.1.css');
await load('./v12.1-patch.js');
css('./v13.css');
css('./v13-assets.css');
await load('./v13-patch.js');
}catch(e){console.error(e);document.body.insertAdjacentHTML('beforeend','<div style="padding:20px">The app failed to start. Reload once; if it persists, report it.</div>')}})();
