(async()=>{
  const VERSION='11.0-alpha';
  const $=id=>document.getElementById(id);
  const loadCatalog=async()=>{
    try{
      const urls=['./data/catalog.part0.b64','./data/catalog.part1.b64','./data/catalog.part2.b64','./data/catalog.part3.b64','./data/catalog.part4.b64'];
      const parts=await Promise.all(urls.map(async u=>{const r=await fetch(u);if(!r.ok)throw new Error(`catalog ${r.status}`);return r.text()}));
      const bin=atob(parts.join(''));const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);
      const text=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();return JSON.parse(text);
    }catch(e){console.error('v11 catalog load failed',e);return {plates:[],jurisdictions:[]}}
  };
  const CATALOG=await loadCatalog();
  const jurMap=Object.fromEntries((CATALOG.jurisdictions||[]).map(j=>[j.id||j.jurisdiction_id,j.name||j.code||j.id]));
  const INDEX=(CATALOG.plates||[]).map(p=>{const v=p.visual||{};return [p.plate_uid,p.name,p.jurisdiction_id,jurMap[p.jurisdiction_id]||p.jurisdiction_id,p.category||'',v.background_primary||'',v.background_secondary||'',v.text_primary||'',v.dominant_motif||'',v.slogan_text||'',v.visual_style||'']});
  const JR={}; INDEX.forEach(p=>JR[p[2]]=p[3]);
  const COLORS=[
    ['','Any','#e9e1cf'],['white','White','#faf8ef'],['black','Black','#171717'],['blue','Blue','#557ea8'],['light_blue','Light blue','#acd2e4'],['dark_blue','Dark blue','#244c77'],['red','Red','#b54f48'],['green','Green','#527a59'],['yellow','Yellow','#e3c253'],['orange','Orange','#d68b45'],['pink','Pink','#e5a8bd'],['purple','Purple','#79638c'],['gray','Gray','#949897'],['brown','Brown','#80654e'],['multicolor','Multi','conic-gradient(#cf6a55,#d7bd55,#5a9670,#6296ba,#a56c9e,#cf6a55)']
  ];
  const COLOR_ALIASES={grey:'gray',navy:'dark_blue',turquoise:'blue',gold:'yellow',crimson:'red',dark_red:'red',dark_green:'green',light_yellow:'yellow',dark_gray:'gray',illustrated:'multicolor',multi:'multicolor'};
  const normColor=v=>COLOR_ALIASES[String(v||'').toLowerCase()]||String(v||'').toLowerCase();
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const R=window.LPG_R||{};
  const refSvg=(spec,uid)=>{
    if(!spec)return `<div class="plate-fallback">${esc((uid.split('-')[2]||'PLATE').slice(0,8))}</div>`;
    const bg=spec[0], ink=spec[1], code=spec[4]||'', slogan=String(spec[2]||'').slice(0,25);
    const cm={white:'#fbfaf4',black:'#161616',blue:'#658cad',light_blue:'#b7d9e8',dark_blue:'#294e75',navy:'#29405e',red:'#b7544d',green:'#53795a',yellow:'#e0bf4d',orange:'#d68943',pink:'#e1a4b9',purple:'#756287',gray:'#999b99',dark_gray:'#4d5252',brown:'#80654d',multicolor:'#cad8cc'};
    const bgc=cm[normColor(bg)]||'#e7e1d4',ic=cm[normColor(ink)]||'#27323a';
    return `<div class="reference-plate"><svg class="lpg-ref-svg" viewBox="0 0 200 100"><rect x="3" y="3" width="194" height="94" rx="9" fill="${bgc}" stroke="${ic}" stroke-width="3"/><text x="100" y="20" text-anchor="middle" fill="${ic}" font-family="Arial" font-size="10" font-weight="700">${esc(code)}</text><text x="100" y="62" text-anchor="middle" fill="${ic}" font-family="Arial" font-size="24" font-weight="800" letter-spacing="3">LPG 000</text>${slogan?`<text x="100" y="84" text-anchor="middle" fill="${ic}" font-family="Arial" font-size="7" font-weight="700">${esc(slogan)}</text>`:''}<text x="187" y="92" text-anchor="end" fill="${ic}" font-family="Arial" font-size="5" opacity=".55">REF</text></svg></div>`;
  };
  const searchable=p=>`${p[1]} ${p[3]} ${p[4]} ${p[8]} ${p[9]} ${p[10]}`.toLowerCase();
  const plateRow=p=>`<article class="result" data-v11-uid="${esc(p[0])}">${refSvg(R[p[0]],p[0])}<div><div class="result-title">${esc(p[1])}</div><div class="result-meta">${esc(p[3])}${p[4]?` · ${esc(p[4])}`:''}</div></div><button class="found-btn" data-add="${esc(p[0])}" aria-label="Add ${esc(p[1])}">+</button></article>`;
  document.body.classList.add('lpg-v11');
  const home=$('home');
  if(home&&!$('researchLaunch')){const launch=document.createElement('button');launch.id='researchLaunch';launch.type='button';launch.className='research-launch v11-kraft v11-pin';launch.innerHTML='<span>Research the plate catalog</span><small>Browse all 1,138 designs →</small>'; (home.querySelector('.home-progress')||home).after(launch)}
  const settings=$('settings');
  if(settings&&!$('settingsResearch')){const grid=settings.querySelector('.settings-grid');const s=document.createElement('div');s.className='setting';s.innerHTML='<h3>Plate research</h3><p>Browse the catalog on a larger screen or just satisfy the very human urge to inspect 1,138 rectangles.</p><button id="settingsResearch" class="action">Open research catalog</button>';grid?.prepend(s)}
  let research=$('research');
  if(!research){research=document.createElement('section');research.id='research';research.className='screen';research.innerHTML=`<div class="research-head"><h1>Plate research</h1><button id="researchBack" class="research-back">← back</button></div><div class="research-toolbar v11-pin"><input id="researchSearch" type="search" placeholder="Search plates…"><select id="researchState"><option value="">All places</option></select><select id="researchCategory"><option value="">All types</option></select></div><div id="researchSummary" class="research-summary"></div><div id="researchResults" class="research-results"></div>`;$('settings')?.before(research)}
  const stateOptions=[...new Map(INDEX.map(p=>[p[2],p[3]])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));
  const categoryOptions=[...new Set(INDEX.map(p=>p[4]).filter(Boolean))].sort();
  $('researchState').innerHTML='<option value="">All places</option>'+stateOptions.map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join('');
  $('researchCategory').innerHTML='<option value="">All types</option>'+categoryOptions.map(n=>`<option>${esc(n)}</option>`).join('');
  const showScreen=id=>{document.querySelectorAll('main>.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));document.body.classList.toggle('lpg-camera-mode',id==='camera')};
  const openResearch=()=>{showScreen('research');renderResearch()};
  $('researchLaunch')?.addEventListener('click',openResearch);$('settingsResearch')?.addEventListener('click',openResearch);$('researchBack')?.addEventListener('click',()=>document.querySelector('[data-screen="home"]')?.click());
  const renderResearch=()=>{const q=$('researchSearch').value.trim().toLowerCase(),st=$('researchState').value,cat=$('researchCategory').value;let rows=INDEX.filter(p=>(!q||searchable(p).includes(q))&&(!st||p[2]===st)&&(!cat||p[4]===cat));rows.sort((a,b)=>a[3].localeCompare(b[3])||a[1].localeCompare(b[1]));$('researchSummary').textContent=`${rows.length.toLocaleString()} design${rows.length===1?'':'s'} · ${Object.keys(R).length.toLocaleString()} currently have public visual references`;$('researchResults').innerHTML=rows.slice(0,250).map(plateRow).join('')+(rows.length>250?`<div class="empty">Showing the first 250. Narrow the search to see the rest.</div>`:'')};
  ['researchSearch','researchState','researchCategory'].forEach(id=>$(id)?.addEventListener(id==='researchSearch'?'input':'change',renderResearch));
  const identify=$('identify');
  if(identify){identify.innerHTML=`<div class="identify-v11"><div class="identify-titleline"><h1>Identify the plate</h1><small>start with the colors<br>then narrow it down</small></div><div id="pendingPhotoBanner" class="v11-photo-slot"></div><div class="identify-toolbox v11-pin"><div class="color-dials"><div class="color-dial" data-dial="bg1"><label>Main background</label><div class="dial-body"><button class="dial-arrow" data-dir="-1">‹</button><button class="dial-face" type="button"><span class="dial-value">Any</span></button><button class="dial-arrow" data-dir="1">›</button></div></div><div class="color-dial" data-dial="bg2"><label>Second color</label><div class="dial-body"><button class="dial-arrow" data-dir="-1">‹</button><button class="dial-face" type="button"><span class="dial-value">Any</span></button><button class="dial-arrow" data-dir="1">›</button></div></div><div class="color-dial" data-dial="text"><label>Letters</label><div class="dial-body"><button class="dial-arrow" data-dir="-1">‹</button><button class="dial-face" type="button"><span class="dial-value">Any</span></button><button class="dial-arrow" data-dir="1">›</button></div></div></div><div class="identify-minor"><input id="v11IdentifySearch" type="search" placeholder="words / team / animal"><select id="v11IdentifyState"><option value="">Any state / province</option></select><button id="v11IdentifyReset" class="identify-reset" aria-label="Clear identification clues">×</button></div><details class="identify-more"><summary>more clues</summary><div class="motif-chips"><button class="motif-chip" data-motif="animal">animal</button><button class="motif-chip" data-motif="mountain">scenic</button><button class="motif-chip" data-motif="flag">flag</button><button class="motif-chip" data-motif="university">school</button><button class="motif-chip" data-motif="military">service</button><button class="motif-chip" data-motif="logo">logo</button></div></details></div><div class="v11-match-head"><strong id="v11IdentifyCount">Choose a clue</strong><span id="v11IdentifyHint">matches stay hidden until then</span></div><div id="v11IdentifyResults" class="v11-results"><div class="v11-idle"><div><b>No wall of rectangles.</b>Use one color dial or type a clue to begin.</div></div></div></div>`}
  $('v11IdentifyState').innerHTML='<option value="">Any state / province</option>'+stateOptions.map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join('');
  const dialState={bg1:0,bg2:0,text:0};let motifFilter='';
  const paintDial=d=>{const el=document.querySelector(`.color-dial[data-dial="${d}"]`),v=COLORS[dialState[d]];if(!el)return;el.querySelector('.dial-face').style.setProperty('--dial',v[2]);el.querySelector('.dial-value').textContent=v[1]};
  const hasIdentifyClue=()=>dialState.bg1||dialState.bg2||dialState.text||$('v11IdentifySearch')?.value.trim()||$('v11IdentifyState')?.value||motifFilter;
  const renderIdentify=()=>{['bg1','bg2','text'].forEach(paintDial);const results=$('v11IdentifyResults');if(!results)return;if(!hasIdentifyClue()){$('v11IdentifyCount').textContent='Choose a clue';$('v11IdentifyHint').textContent='matches stay hidden until then';results.innerHTML='<div class="v11-idle"><div><b>No wall of rectangles.</b>Use one color dial or type a clue to begin.</div></div>';return}const c1=COLORS[dialState.bg1][0],c2=COLORS[dialState.bg2][0],ct=COLORS[dialState.text][0],q=$('v11IdentifySearch').value.trim().toLowerCase(),st=$('v11IdentifyState').value;let rows=INDEX.filter(p=>{const b1=normColor(p[5]),b2=normColor(p[6]),tx=normColor(p[7]),txt=searchable(p);const motifTxt=`${p[4]} ${p[8]} ${p[10]} ${p[1]}`.toLowerCase();return(!c1||b1===c1)&&(!c2||b2===c2||(!b2&&b1===c2))&&(!ct||tx===ct)&&(!q||txt.includes(q))&&(!st||p[2]===st)&&(!motifFilter||motifTxt.includes(motifFilter))});rows.sort((a,b)=>Number(!!R[b[0]])-Number(!!R[a[0]])||a[3].localeCompare(b[3])||a[1].localeCompare(b[1]));$('v11IdentifyCount').textContent=`${rows.length.toLocaleString()} possible`;$('v11IdentifyHint').textContent=rows.length>80?'showing best 80':'tap + when you have it';results.innerHTML=rows.length?rows.slice(0,80).map(plateRow).join(''):'<div class="v11-idle"><div><b>No match yet.</b>Back one dial off or clear a clue.</div></div>'};
  document.querySelectorAll('.color-dial').forEach(el=>{const d=el.dataset.dial;el.querySelectorAll('.dial-arrow').forEach(b=>b.addEventListener('click',()=>{dialState[d]=(dialState[d]+Number(b.dataset.dir)+COLORS.length)%COLORS.length;renderIdentify()}));el.querySelector('.dial-face').addEventListener('click',()=>{dialState[d]=(dialState[d]+1)%COLORS.length;renderIdentify()});paintDial(d)});
  $('v11IdentifySearch')?.addEventListener('input',renderIdentify);$('v11IdentifyState')?.addEventListener('change',renderIdentify);
  document.querySelectorAll('.motif-chip').forEach(b=>b.addEventListener('click',()=>{motifFilter=motifFilter===b.dataset.motif?'':b.dataset.motif;document.querySelectorAll('.motif-chip').forEach(x=>x.classList.toggle('active',x.dataset.motif===motifFilter));renderIdentify()}));
  $('v11IdentifyReset')?.addEventListener('click',()=>{dialState.bg1=dialState.bg2=dialState.text=0;motifFilter='';$('v11IdentifySearch').value='';$('v11IdentifyState').value='';document.querySelectorAll('.motif-chip').forEach(x=>x.classList.remove('active'));renderIdentify()});
  renderIdentify();
  const absorbPhoto=()=>{const old=document.querySelector('#pendingPhotoBanner .attached-photo');if(old)$('pendingPhotoBanner')?.classList.add('has-photo')};new MutationObserver(absorbPhoto).observe($('pendingPhotoBanner')||document.body,{subtree:true,childList:true});
  window.addEventListener('scroll',()=>{if(!document.body.classList.contains('lpg-camera-mode')&&window.scrollY)window.scrollTo(0,0)},{passive:true});
  document.documentElement.dataset.lpgVersion=VERSION;
  if(settings&&!$('v11VersionSlip')){const s=document.createElement('div');s.id='v11VersionSlip';s.className='setting';s.innerHTML=`<h3>App version</h3><p><b>${VERSION}</b> · installed PWA and web companion use the same codebase. Cloud login/sync is the next backend layer; local play remains usable without an account.</p>`;settings.querySelector('.settings-grid')?.appendChild(s)}
})();
